name: Generate README.md

on:
  workflow_run:
    workflows: ["Main ReadMe Updater"]
    branches: [main]
    types: 
      - completed

  workflow_dispatch:


jobs:
  UpdateStatsTemplate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1.2
      with:
        token: ${{ secrets.G_TOKEN }}
        includeForks: true
        template: ./README.md
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Updated Readme - step 2"
        git push --all -f https://${{ secrets.G_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        fi
